/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package princetonPlainsboro;

import javax.swing.JList;
import javax.swing.ListModel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Go.0
 */
public class MainWindow extends javax.swing.JFrame {
    
    private DossierMedical dm;

    /** Creates new form NewJFrame */
    public MainWindow() {
        this.setTitle("Prinston-Plainsboro    Gestion des dossiers médicaux");
        initComponents();

        LectureXML test = new LectureXML("dossiers.xml");
        this.dm = test.getDossier();
        
        initPatientTab();
        initMedecinTab();
        initFichesTab();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jMenu1 = new javax.swing.JMenu();
        jDialog1 = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        mainTabbedPanel = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        fichesLst = new javax.swing.JList<>();
        jButton11 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        ficheMedecinTxtF = new javax.swing.JTextField();
        fichePatientTxtF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ficheDateTxtF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ficheTypeActeTxtF = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        ficheCoutActeTxtf = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ficheObservationsTxtf = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        fichesActesCBox = new javax.swing.JComboBox<>();
        medecinPnl = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        medecinLst = new javax.swing.JList<>();
        jButton6 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        saveMedecinBtn = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        medecinNameTxtF = new javax.swing.JTextField();
        medecinSpecialiteTxtF = new javax.swing.JTextField();
        telephoneTxtF = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        medecinSurnameTxtF = new javax.swing.JTextField();
        editMedecinBtn = new javax.swing.JToggleButton();
        patientPnl = new javax.swing.JPanel();
        patientSPnl = new javax.swing.JSplitPane();
        patientListPnl = new javax.swing.JPanel();
        patientListScroll = new javax.swing.JScrollPane();
        patientLst = new javax.swing.JList<>();
        addPatientBtn = new javax.swing.JButton();
        addPatientBtn1 = new javax.swing.JButton();
        viewPatientPnl = new javax.swing.JPanel();
        printPatientBtn = new javax.swing.JButton();
        savePatientBtn = new javax.swing.JButton();
        addActePatientBtn = new javax.swing.JButton();
        infoPatientPnl = new javax.swing.JPanel();
        nameLbl = new javax.swing.JLabel();
        surnameLbl = new javax.swing.JLabel();
        adressLbl = new javax.swing.JLabel();
        patientNameTxtF = new javax.swing.JTextField();
        patientSurnameTxtF = new javax.swing.JTextField();
        patientAdressTxtF = new javax.swing.JTextField();
        patientInseeLbl = new javax.swing.JLabel();
        patientInseeTxtF = new javax.swing.JTextField();
        listeActePatientLbl = new javax.swing.JLabel();
        listeActePatientSPnl = new javax.swing.JScrollPane();
        listeActepatientTbl = new javax.swing.JTable();
        editPatientBtn = new javax.swing.JToggleButton();
        jPanel8 = new javax.swing.JPanel();

        jMenuItem1.setText("jMenuItem1");

        jLabel2.setText("jLabel2");

        jMenu1.setText("jMenu1");

        org.jdesktop.layout.GroupLayout jDialog1Layout = new org.jdesktop.layout.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout jPanel9Layout = new org.jdesktop.layout.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainTabbedPanel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mainTabbedPanel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mainTabbedPanelStateChanged(evt);
            }
        });

        jSplitPane3.setDividerLocation(300);
        jSplitPane3.setDividerSize(8);

        fichesLst.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(fichesLst);

        jButton11.setText("Ajouter");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setText("Trier par :");

        org.jdesktop.layout.GroupLayout jPanel14Layout = new org.jdesktop.layout.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel14Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel14Layout.createSequentialGroup()
                        .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(jPanel14Layout.createSequentialGroup()
                        .add(23, 23, 23)
                        .add(jButton11)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabel12)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jComboBox3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(30, 30, 30))))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel14Layout.createSequentialGroup()
                .add(14, 14, 14)
                .add(jPanel14Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton11)
                    .add(jComboBox3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel12))
                .add(18, 18, 18)
                .add(jScrollPane4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane3.setLeftComponent(jPanel14);

        jButton12.setText("Imprimer");

        jButton13.setText("Modifier");

        jButton14.setText("Enregistrer");

        jButton15.setText("Ajouter un acte");

        jLabel13.setText("Nom de l'acte :");

        jLabel14.setText("Nom du médecin :");

        jLabel15.setText("Nom du patient :");

        jTextField8.setEditable(false);

        ficheMedecinTxtF.setEditable(false);

        fichePatientTxtF.setEditable(false);

        jLabel16.setText("Date :");

        ficheDateTxtF.setEditable(false);

        jLabel17.setText("Type :");

        ficheTypeActeTxtF.setEditable(false);

        jLabel18.setText("Coût :");

        ficheCoutActeTxtf.setEditable(false);

        jLabel19.setText("Observations :");

        ficheObservationsTxtf.setEditable(false);
        ficheObservationsTxtf.setColumns(20);
        ficheObservationsTxtf.setRows(5);
        jScrollPane5.setViewportView(ficheObservationsTxtf);

        jLabel1.setText("Acte :");

        fichesActesCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new Acte[] {  }));
        fichesActesCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fichesActesCBoxActionPerformed(evt);
            }
        });
        fichesActesCBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fichesActesCBoxPropertyChange(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel16Layout = new org.jdesktop.layout.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel16Layout.createSequentialGroup()
                .add(24, 24, 24)
                .add(jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel16Layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(18, 18, 18)
                        .add(fichesActesCBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel16Layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jLabel19)
                        .add(18, 18, 18)
                        .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 424, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel16Layout.createSequentialGroup()
                        .add(jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel16Layout.createSequentialGroup()
                                .add(jLabel13)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jTextField8))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel16Layout.createSequentialGroup()
                                .add(jLabel14)
                                .add(14, 14, 14)
                                .add(ficheMedecinTxtF))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel16Layout.createSequentialGroup()
                                .add(jLabel15)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(fichePatientTxtF))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel16Layout.createSequentialGroup()
                                .add(jLabel16)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(ficheDateTxtF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 459, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel16Layout.createSequentialGroup()
                                .add(jLabel17)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(ficheTypeActeTxtF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 417, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel16Layout.createSequentialGroup()
                                .add(jLabel18)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(ficheCoutActeTxtf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 417, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(44, 44, 44)))
                .add(170, 170, 170))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel16Layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(ficheDateTxtF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel16))
                .add(18, 18, 18)
                .add(jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel14)
                    .add(ficheMedecinTxtF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(15, 15, 15)
                .add(jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel15)
                    .add(fichePatientTxtF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(fichesActesCBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(28, 28, 28)
                .add(jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel13)
                    .add(jTextField8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel17)
                    .add(ficheTypeActeTxtF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel18)
                    .add(ficheCoutActeTxtf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel19)
                    .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(372, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel15Layout = new org.jdesktop.layout.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel15Layout.createSequentialGroup()
                .add(50, 50, 50)
                .add(jButton13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(33, 33, 33)
                .add(jButton14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(27, 27, 27)
                .add(jButton12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButton15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 132, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(36, 36, 36))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel16, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel15Layout.createSequentialGroup()
                .add(16, 16, 16)
                .add(jPanel15Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane3.setRightComponent(jPanel15);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jSplitPane3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jSplitPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainTabbedPanel.addTab("Fiches de soins", jPanel3);

        jSplitPane2.setDividerLocation(300);
        jSplitPane2.setDividerSize(8);

        medecinLst.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(medecinLst);

        jButton6.setText("Ajouter");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Trier par :");

        org.jdesktop.layout.GroupLayout jPanel10Layout = new org.jdesktop.layout.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel10Layout.createSequentialGroup()
                        .add(jScrollPane3)
                        .addContainerGap())
                    .add(jPanel10Layout.createSequentialGroup()
                        .add(23, 23, 23)
                        .add(jButton6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 44, Short.MAX_VALUE)
                        .add(jLabel8)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jComboBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(30, 30, 30))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel10Layout.createSequentialGroup()
                .add(14, 14, 14)
                .add(jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton6)
                    .add(jComboBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8))
                .add(18, 18, 18)
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane2.setLeftComponent(jPanel10);

        saveMedecinBtn.setText("Enregistrer");
        saveMedecinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMedecinBtnActionPerformed(evt);
            }
        });

        jLabel9.setText("Nom :");

        jLabel10.setText("Spécialité :");

        jLabel11.setText("Numéro de téléphone :");

        medecinNameTxtF.setEditable(false);

        medecinSpecialiteTxtF.setEditable(false);

        telephoneTxtF.setEditable(false);

        jLabel20.setText("Prénom :");

        medecinSurnameTxtF.setEditable(false);

        org.jdesktop.layout.GroupLayout jPanel12Layout = new org.jdesktop.layout.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel12Layout.createSequentialGroup()
                .add(17, 17, 17)
                .add(jPanel12Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel12Layout.createSequentialGroup()
                        .add(jLabel20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(medecinSurnameTxtF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 230, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel12Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jPanel12Layout.createSequentialGroup()
                            .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                            .add(medecinNameTxtF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 230, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanel12Layout.createSequentialGroup()
                            .add(jLabel10)
                            .add(14, 14, 14)
                            .add(medecinSpecialiteTxtF))
                        .add(jPanel12Layout.createSequentialGroup()
                            .add(jLabel11)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(telephoneTxtF))))
                .addContainerGap(410, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel12Layout.createSequentialGroup()
                .add(35, 35, 35)
                .add(jPanel12Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel9)
                    .add(medecinNameTxtF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel12Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel20)
                    .add(medecinSurnameTxtF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel12Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel10)
                    .add(medecinSpecialiteTxtF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel12Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel11)
                    .add(telephoneTxtF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(512, Short.MAX_VALUE))
        );

        editMedecinBtn.setText("Modifier");
        editMedecinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMedecinBtnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel11Layout = new org.jdesktop.layout.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel11Layout.createSequentialGroup()
                .add(42, 42, 42)
                .add(editMedecinBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 89, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(52, 52, 52)
                .add(saveMedecinBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel12, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel11Layout.createSequentialGroup()
                .add(16, 16, 16)
                .add(jPanel11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(saveMedecinBtn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .add(editMedecinBtn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(jPanel12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(jPanel11);

        org.jdesktop.layout.GroupLayout medecinPnlLayout = new org.jdesktop.layout.GroupLayout(medecinPnl);
        medecinPnl.setLayout(medecinPnlLayout);
        medecinPnlLayout.setHorizontalGroup(
            medecinPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(medecinPnlLayout.createSequentialGroup()
                .addContainerGap()
                .add(jSplitPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
                .addContainerGap())
        );
        medecinPnlLayout.setVerticalGroup(
            medecinPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(medecinPnlLayout.createSequentialGroup()
                .addContainerGap()
                .add(jSplitPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainTabbedPanel.addTab("Médecins", medecinPnl);

        patientSPnl.setDividerLocation(300);
        patientSPnl.setDividerSize(8);

        patientLst.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        patientListScroll.setViewportView(patientLst);

        addPatientBtn.setText("Filtrer");
        addPatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientBtnActionPerformed(evt);
            }
        });

        addPatientBtn1.setText("Ajouter");
        addPatientBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientBtn1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout patientListPnlLayout = new org.jdesktop.layout.GroupLayout(patientListPnl);
        patientListPnl.setLayout(patientListPnlLayout);
        patientListPnlLayout.setHorizontalGroup(
            patientListPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(patientListPnlLayout.createSequentialGroup()
                .addContainerGap()
                .add(patientListScroll, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, patientListPnlLayout.createSequentialGroup()
                .add(44, 44, 44)
                .add(addPatientBtn1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(addPatientBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(23, 23, 23))
        );
        patientListPnlLayout.setVerticalGroup(
            patientListPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(patientListPnlLayout.createSequentialGroup()
                .addContainerGap()
                .add(patientListPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(addPatientBtn1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .add(addPatientBtn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(patientListScroll, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addContainerGap())
        );

        patientSPnl.setLeftComponent(patientListPnl);

        printPatientBtn.setText("Imprimer");
        printPatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printPatientBtnActionPerformed(evt);
            }
        });

        savePatientBtn.setText("Enregistrer");
        savePatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePatientBtnActionPerformed(evt);
            }
        });

        addActePatientBtn.setText("Ajouter un acte");

        nameLbl.setText("Nom :");

        surnameLbl.setText("Prénom :");

        adressLbl.setText("Adresse :");

        patientNameTxtF.setEditable(false);

        patientSurnameTxtF.setEditable(false);

        patientAdressTxtF.setEditable(false);

        patientInseeLbl.setText("INSEE :");

        patientInseeTxtF.setEditable(false);

        listeActePatientLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        listeActePatientLbl.setText("Liste des actes médicaux du patient : ");

        listeActepatientTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom de l'acte", "Nom du médecin", "Date de réalisation", "Code des coûts", "Coût total ( € )"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listeActePatientSPnl.setViewportView(listeActepatientTbl);
        if (listeActepatientTbl.getColumnModel().getColumnCount() > 0) {
            listeActepatientTbl.getColumnModel().getColumn(0).setResizable(false);
            listeActepatientTbl.getColumnModel().getColumn(1).setResizable(false);
            listeActepatientTbl.getColumnModel().getColumn(2).setResizable(false);
            listeActepatientTbl.getColumnModel().getColumn(3).setResizable(false);
            listeActepatientTbl.getColumnModel().getColumn(4).setResizable(false);
        }

        org.jdesktop.layout.GroupLayout infoPatientPnlLayout = new org.jdesktop.layout.GroupLayout(infoPatientPnl);
        infoPatientPnl.setLayout(infoPatientPnlLayout);
        infoPatientPnlLayout.setHorizontalGroup(
            infoPatientPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(infoPatientPnlLayout.createSequentialGroup()
                .add(17, 17, 17)
                .add(infoPatientPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(infoPatientPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(infoPatientPnlLayout.createSequentialGroup()
                            .add(nameLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                            .add(patientNameTxtF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 230, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(infoPatientPnlLayout.createSequentialGroup()
                            .add(surnameLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(18, 18, 18)
                            .add(patientSurnameTxtF))
                        .add(infoPatientPnlLayout.createSequentialGroup()
                            .add(adressLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(18, 18, 18)
                            .add(patientAdressTxtF)))
                    .add(infoPatientPnlLayout.createSequentialGroup()
                        .add(patientInseeLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 68, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(patientInseeTxtF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 312, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(listeActePatientLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 339, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(listeActePatientSPnl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 679, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        infoPatientPnlLayout.setVerticalGroup(
            infoPatientPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(infoPatientPnlLayout.createSequentialGroup()
                .add(35, 35, 35)
                .add(infoPatientPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(nameLbl)
                    .add(patientNameTxtF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(infoPatientPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(surnameLbl)
                    .add(patientSurnameTxtF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(15, 15, 15)
                .add(infoPatientPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(adressLbl)
                    .add(patientAdressTxtF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(infoPatientPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(patientInseeLbl)
                    .add(patientInseeTxtF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(32, 32, 32)
                .add(listeActePatientLbl)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(listeActePatientSPnl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 270, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        editPatientBtn.setText("Modifier");
        editPatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPatientBtnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout viewPatientPnlLayout = new org.jdesktop.layout.GroupLayout(viewPatientPnl);
        viewPatientPnl.setLayout(viewPatientPnlLayout);
        viewPatientPnlLayout.setHorizontalGroup(
            viewPatientPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, viewPatientPnlLayout.createSequentialGroup()
                .add(24, 24, 24)
                .add(editPatientBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(30, 30, 30)
                .add(savePatientBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(27, 27, 27)
                .add(printPatientBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 196, Short.MAX_VALUE)
                .add(addActePatientBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 132, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(36, 36, 36))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, viewPatientPnlLayout.createSequentialGroup()
                .addContainerGap()
                .add(infoPatientPnl, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        viewPatientPnlLayout.setVerticalGroup(
            viewPatientPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(viewPatientPnlLayout.createSequentialGroup()
                .add(16, 16, 16)
                .add(viewPatientPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(viewPatientPnlLayout.createSequentialGroup()
                        .add(viewPatientPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(savePatientBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(printPatientBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(addActePatientBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(editPatientBtn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(infoPatientPnl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        patientSPnl.setRightComponent(viewPatientPnl);

        org.jdesktop.layout.GroupLayout patientPnlLayout = new org.jdesktop.layout.GroupLayout(patientPnl);
        patientPnl.setLayout(patientPnlLayout);
        patientPnlLayout.setHorizontalGroup(
            patientPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(patientPnlLayout.createSequentialGroup()
                .addContainerGap()
                .add(patientSPnl)
                .addContainerGap())
        );
        patientPnlLayout.setVerticalGroup(
            patientPnlLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(patientPnlLayout.createSequentialGroup()
                .addContainerGap()
                .add(patientSPnl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainTabbedPanel.addTab("Patients", patientPnl);

        org.jdesktop.layout.GroupLayout jPanel8Layout = new org.jdesktop.layout.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1056, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 606, Short.MAX_VALUE)
        );

        mainTabbedPanel.addTab("Prix", jPanel8);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainTabbedPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainTabbedPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initPatientTab() {
        JList patientJList = new JList(dm.getPatientsNames().toArray());
        this.patientLst.setFixedCellHeight(30);
        this.patientLst.setModel(patientJList.getModel());
        this.patientLst.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        ListSelectionModel listSelectionModel = this.patientLst.getSelectionModel();
        listSelectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                try {
                    Patient selectedPatient = dm.getPatient(patientLst.getSelectedValue());
                    updatePatientTextFields(selectedPatient);

                    DefaultTableModel model = (DefaultTableModel) MainWindow.this.listeActepatientTbl.getModel();
                    model.getDataVector().removeAllElements();
                    model.fireTableDataChanged(); 
                    for(Acte a: selectedPatient.getlisteActes()){
                        model.addRow(a.toArray());
                    }
                } catch (Exception e) {
                    
                }
            }
        }); 
    }
    
    private void initMedecinTab() {
        JList medecinJList = new JList(dm.getMedecinsNames().toArray());
        this.medecinLst.setFixedCellHeight(30);
        this.medecinLst.setModel(medecinJList.getModel());
        this.medecinLst.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        ListSelectionModel listSelectionModel = this.medecinLst.getSelectionModel();
        listSelectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                try {
                    Medecin selectedMedecin = dm.getMedecin(medecinLst.getSelectedValue());
                    updateMedecinTextFields(selectedMedecin);

                    
                } catch (Exception e) {
                    
                }
            }
        }); 
    }
    
    private void initFichesTab(){
        JList fichesJList = new JList(dm.getFichesNames().toArray());
        this.fichesLst.setFixedCellHeight(30);
        this.fichesLst.setModel(fichesJList.getModel());
        this.fichesLst.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        
        ListSelectionModel listSelectionModel = this.fichesLst.getSelectionModel();
        listSelectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                try {
                    FicheDeSoins selectedFiche = dm.getFiche(fichesLst.getSelectedValue());
                    updateFicheTextFields(selectedFiche);


                } catch (Exception e) { }
            }
        }); 
    }
    private void addPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPatientBtnActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void printPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printPatientBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printPatientBtnActionPerformed

    private void editPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPatientBtnActionPerformed
        if(this.editPatientBtn.getText().equals("Modifier")) {
            this.editPatientBtn.setText("Annuler");
            this.patientAdressTxtF.setEditable(true);
            this.patientNameTxtF.setEditable(true);
            this.patientSurnameTxtF.setEditable(true);
            this.patientInseeTxtF.setEditable(true);
        } else {
            this.editPatientBtn.setText("Modifier");
            this.patientAdressTxtF.setEditable(false);
            this.patientNameTxtF.setEditable(false);
            this.patientSurnameTxtF.setEditable(false);
            this.patientInseeTxtF.setEditable(false);
            Patient selectedPatient = dm.getPatient(patientLst.getSelectedValue());
            updatePatientTextFields(selectedPatient);
        }
    }//GEN-LAST:event_editPatientBtnActionPerformed

    private void savePatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePatientBtnActionPerformed
        Patient selectedPatient = dm.getPatient(patientLst.getSelectedValue());
        
        int patientIndex = this.patientLst.getSelectedIndex();
        
        selectedPatient.setNom( this.patientNameTxtF.getText() );
        selectedPatient.setPrenom( this.patientSurnameTxtF.getText() );
        
        JList patientJList = new JList(dm.getPatientsNames().toArray());
        
        this.patientLst.setModel(patientJList.getModel());
        this.patientLst.setSelectedIndex( patientIndex );
        this.editPatientBtn.setSelected(false);
        this.editPatientBtn.setText("Modifier");
    }//GEN-LAST:event_savePatientBtnActionPerformed

    private void addPatientBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientBtn1ActionPerformed
        int patientIndex = this.patientLst.getSelectedIndex();
        AddPatient ap = new AddPatient(this);
        ap.setVisible(true);
        ap.setLocationRelativeTo(null);
        ap.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        JList patientJList = new JList(dm.getPatientsNames().toArray());
        this.patientLst.setModel(patientJList.getModel());
        this.patientLst.setSelectedIndex( patientIndex );
        
    }//GEN-LAST:event_addPatientBtn1ActionPerformed

    private void mainTabbedPanelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mainTabbedPanelStateChanged
//        JTabbedPane t = (JTabbedPane) evt.getSource();
//        int selectedIndex = t.getSelectedIndex();
//        
//        switch(selectedIndex){
//            case 0:
//                System.out.println("0");
//            case 1:
//                System.out.println("1");
//            case 2:
//                System.out.println("2");
//        }
        
    }//GEN-LAST:event_mainTabbedPanelStateChanged

    private void editMedecinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMedecinBtnActionPerformed
        if(this.editMedecinBtn.getText().equals("Modifier")) {
            this.editMedecinBtn.setText("Annuler");
            this.medecinNameTxtF.setEditable(true);
            this.medecinSurnameTxtF.setEditable(true);
            this.medecinSpecialiteTxtF.setEditable(true);
        } else {
            this.editMedecinBtn.setText("Modifier");
            this.medecinNameTxtF.setEditable(false);
            this.medecinSurnameTxtF.setEditable(false);
            this.medecinSpecialiteTxtF.setEditable(false);
            Medecin selectedMedecin = dm.getMedecin(medecinLst.getSelectedValue());
            updateMedecinTextFields(selectedMedecin);
        }
    }//GEN-LAST:event_editMedecinBtnActionPerformed

    private void saveMedecinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMedecinBtnActionPerformed
        Medecin selectedMedecin = dm.getMedecin(medecinLst.getSelectedValue());
        
        int selectIndex = this.patientLst.getSelectedIndex();
        
        selectedMedecin.setNom( this.medecinNameTxtF.getText() );
        selectedMedecin.setPrenom( this.medecinSurnameTxtF.getText() );
        selectedMedecin.setSpecialite( this.medecinSpecialiteTxtF.getText() );
        
        JList patientJList = new JList(dm.getMedecinsNames().toArray());
        
        this.medecinLst.setModel(patientJList.getModel());
        this.medecinLst.setSelectedIndex( selectIndex );
        this.editMedecinBtn.setSelected(false);
        this.editMedecinBtn.setText("Modifier");
    }//GEN-LAST:event_saveMedecinBtnActionPerformed

    private void fichesActesCBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fichesActesCBoxPropertyChange
         
        try{
            JComboBox c = (JComboBox) evt.getSource();
            Acte a = (Acte)c.getSelectedItem();
            MainWindow.this.ficheCoutActeTxtf.setText( Double.toString( a.cout() ));
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_fichesActesCBoxPropertyChange

    private void fichesActesCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fichesActesCBoxActionPerformed
         try{
            JComboBox c = (JComboBox) evt.getSource();
            Acte a = (Acte)c.getSelectedItem();
            MainWindow.this.ficheCoutActeTxtf.setText( Double.toString( a.cout() ));
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_fichesActesCBoxActionPerformed
    
    private void updatePatientTextFields(Patient p){
        MainWindow.this.patientNameTxtF.setText( p.getNom() );
        MainWindow.this.patientSurnameTxtF.setText( p.getPrenom() );
    }
    
    private void updateMedecinTextFields(Medecin m){
        MainWindow.this.medecinNameTxtF.setText( m.getNom() );
        MainWindow.this.medecinSurnameTxtF.setText( m.getPrenom() );
        MainWindow.this.medecinSpecialiteTxtF.setText( m.getSpecialite() );
    }
    
    private void updateFicheTextFields(FicheDeSoins f){
        MainWindow.this.ficheMedecinTxtF.setText( f.getMedecin().toString() );
        MainWindow.this.fichePatientTxtF.setText( f.getPatient().toString() );
        MainWindow.this.ficheDateTxtF.setText( f.getDate().toString() );
        
        
        DefaultComboBoxModel<Acte> model = new DefaultComboBoxModel<>( f.getActes() );
        MainWindow.this.fichesActesCBox.setModel(model);
        
    }
    
    public void ajouterPatient(Patient p){
        int patientIndex = this.patientLst.getSelectedIndex();
        dm.ajouterPatient(p);
        JList patientJList = new JList(dm.getPatientsNames().toArray());
        this.patientLst.setModel(patientJList.getModel());
        this.patientLst.setSelectedIndex( patientIndex );
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainWindow mw = new MainWindow();
                mw.setVisible(true);
                mw.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addActePatientBtn;
    private javax.swing.JButton addPatientBtn;
    private javax.swing.JButton addPatientBtn1;
    private javax.swing.JLabel adressLbl;
    private javax.swing.JToggleButton editMedecinBtn;
    private javax.swing.JToggleButton editPatientBtn;
    private javax.swing.JTextField ficheCoutActeTxtf;
    private javax.swing.JTextField ficheDateTxtF;
    private javax.swing.JTextField ficheMedecinTxtF;
    private javax.swing.JTextArea ficheObservationsTxtf;
    private javax.swing.JTextField fichePatientTxtF;
    private javax.swing.JTextField ficheTypeActeTxtF;
    private javax.swing.JComboBox<Acte> fichesActesCBox;
    private javax.swing.JList<String> fichesLst;
    private javax.swing.JPanel infoPatientPnl;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel listeActePatientLbl;
    private javax.swing.JScrollPane listeActePatientSPnl;
    private javax.swing.JTable listeActepatientTbl;
    private javax.swing.JTabbedPane mainTabbedPanel;
    private javax.swing.JList<String> medecinLst;
    private javax.swing.JTextField medecinNameTxtF;
    private javax.swing.JPanel medecinPnl;
    private javax.swing.JTextField medecinSpecialiteTxtF;
    private javax.swing.JTextField medecinSurnameTxtF;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField patientAdressTxtF;
    private javax.swing.JLabel patientInseeLbl;
    private javax.swing.JTextField patientInseeTxtF;
    private javax.swing.JPanel patientListPnl;
    private javax.swing.JScrollPane patientListScroll;
    private javax.swing.JList<String> patientLst;
    private javax.swing.JTextField patientNameTxtF;
    private javax.swing.JPanel patientPnl;
    private javax.swing.JSplitPane patientSPnl;
    private javax.swing.JTextField patientSurnameTxtF;
    private javax.swing.JButton printPatientBtn;
    private javax.swing.JButton saveMedecinBtn;
    private javax.swing.JButton savePatientBtn;
    private javax.swing.JLabel surnameLbl;
    private javax.swing.JTextField telephoneTxtF;
    private javax.swing.JPanel viewPatientPnl;
    // End of variables declaration//GEN-END:variables

}
